### ISSUE TITLE
Pending authorizations rate limit

### ISSUE THREAD

**Issue by svenba** [skoerfgen/ACMECert#13]
Hi, the limit of pending authorizations is at 300 per account. Is this lib making sure those are always getting trigger to avoid reaching the pending limit? Thanks!

**Comment by skoerfgen** [comment]
Hi!

It works like this:

- for each domain a corresponding authorization (which has currently a [lifetime of 30 days](https://github.com/letsencrypt/boulder/blob/master/test/config-next/ra.json#L10)) is created in `pending` state by Let's Encrypt.
- during the validation process (when the challenge callback returns) the corresponding authorization is triggered and transistions from `pending` to `valid`/`invalid`.

So if there was no error, there are no more pending authorizations left.

On the other hand, when there was a validation error (or the validation process is interrupted otherwise), all remaining/subsequent authorizations stay in pending state.

When you then run getCertificateChain again (after fixing the validation errors) it reuses the pending authz from above.

So pending authorizations can only accumulate, if there are errors during the validation process which do not get resolved (by fixing the validation error(s) and re-running getCertificateChain).

Hope that helps!

**Comment by svenba** [comment]
Thanks a lot for the detailed explanation.

And a authorization in `pending` has a lifetime of 7 days, correct? So the limit of 300 has a sliding window.

It would be good if there is a helper function which allows to trigger the validation of `pending` authorizations (based on the authorization URLs found in the logs) or do you think it is as good to run getCertificateChain again?

**Comment by skoerfgen** [comment]
> And a authorization in `pending` has a lifetime of 7 days, correct? So the limit of 300 has a sliding window.

Both correct!

For pending authorizations it is [7 days](https://github.com/letsencrypt/boulder/blob/ea231adc36746cce97f860e818c2cdf92f060543/test/config-next/ra.json#L11) and for `valid` authorizations it is [30 days](https://github.com/letsencrypt/boulder/blob/ea231adc36746cce97f860e818c2cdf92f060543/test/config-next/ra.json#L10)

> It would be good if there is a helper function which allows to trigger the validation of pending authorizations (based on the authorization URLs found in the logs) or do you think it is as good to run getCertificateChain again?

It is as good as running getCertificateChain again, because of authorization reuse, you will get the same authorization urls again (as long as they are not expired yet). So there is no need to get the urls from the log.

**Comment by svenba** [comment]
Awesome, thanks a lot for the clarification. A little FAQ would be nice and a donation link :)

**Comment by skoerfgen** [comment]
@svenba

You're welcome!

Meanwhile I also have added a [donation link](https://github.com/skoerfgen/ACMECert#donate) :)

Not sure about what topics to cover in the FAQ.. 
(I'm open to suggestions)
