### ISSUE TITLE
Virtual subdomain issues

### ISSUE THREAD

**Issue by gitleif** [skoerfgen/ACMECert#24]
I am creating a multitenant solution in PHP, every user that signup will get a subdomain name like e.g john.domain.com, peter.domain.com.

Im using a DNS TXT record to route all subdomains to www.domain.com, where I do some PHP magic to extract the subdomain name, e.g john and then server john the correct content.

Of course I want the john.domain.com to be secure, using let's encrypt certificate, so that the user have to enter https://john.domain.com

As far as I understand I have to run a function on every signup, e.g when john signup I have to issue a new certificate on the subdomain john.domain.com using this code:

`$domain_config=array('john.example.com'=>array('challenge'=>'dns-01'));`

And then every 80 days or so I have to run through all subdomains to revalidate them, something like this:
```
$domain_config=array('john.example.com'=>array('challenge'=>'dns-01'));
$domain_config=array('peter.example.com'=>array('challenge'=>'dns-01'));
```

Is this correct or am I completely wrong?

Or is a better approach using:

`$domain_config=array('*.example.com'=>array('challenge'=>'dns-01'))`

**Comment by skoerfgen** [comment]
Both approaches are possible but I would recommend the 

```$domain_config=array('*.example.com'=>array('challenge'=>'dns-01'))```

approach. This way you only have to renew one certificate each time instead of multiple and you don't have to create a new one each time someone new signs up. (It also prevents running into [rate limits](https://letsencrypt.org/docs/rate-limits/), in case you get more than 50 signups per week)
