### ISSUE TITLE
[dns-01] A way for delaying?

### ISSUE THREAD

**Issue by Bizarrus** [skoerfgen/ACMECert#4]
Not all DNS servers have a fast TTL. A DNS entry can take up to 24/48 hours to be published.

Is there a way to get the callanges without waiting for the ACME protocol?

I would like to use a database entry that first makes DNS requests before it is processed by the ACME protocol to ensure that the `_acme-challenge?  entry is already published.

If I solve the whole thing (as it exists now in the example) via a cronjob, then the process waits until if i execute the script further. It generates creates overhead unnecessarily.

```php
case 'dns-01':
    echo 'Create DNS-TXT-Record '.$opts['key'].' with value '.$opts['value']."\n";

    // Wait here up to 24/48 hours, because the DNS entry is not published
    // If the _acme-challenge with $opts['value'] is currently not available
    // the script will be waiting here, but it generates lots of overhead because
    // the script is here running all the time until the challenges exist
    // and the script then continues

    return function($opts){
        echo 'Remove DNS-TXT-Record '.$opts['key'].' with value '.$opts['value']."\n";
     };
break;
```

**Comment by skoerfgen** [comment]
The TTL is probably not the problem since on the first validation the Let's Encrypt DNS Resolver doesn't have the TXT Record cached and fetches it directly from the authoritative nameserver(s) for the domain. Problems can occur if a second validation is carried out within 5 minutes for the same domain (Let's Encrypt queries the authoritative nameservers directly - bypassing all other DNS caches - with a max TTL of 5 minutes), in this case the Let's Encrypt DNS Resolver has still the old TXT Record cached and the second validation would fail. (A fix for this case would be a simple `sleep(300);`)

Or maybe your DNS provider does not update the nameserver settings in realtime and there is a delay (Which is different from the TTL) between setting the new TXT Record and when the a authoritative nameserver(s) respond with the new TXT Record.

See also: https://community.letsencrypt.org/t/renewing-with-slow-dns/37918


> Is there a way to get the callanges without waiting for the ACME protocol?

With the current version of ACMECert this isn't possible.

**Comment by Bizarrus** [comment]
Is it possible in further releases?

For currently usage it is possible to split the certain method or it is an problem for ACME  protocol?

On manual usage, i had used certbot. Here i had waiting up to hours before i had continue the process

**Comment by skoerfgen** [comment]
It is absolutely no problem for the ACME protocol. And sure, it is possible to split the getCertificateChain function in two parts (one getting the challenges and the other doing the verification/getting the certificate). But I have no plans including this into ACMECert because the existing getCertificateChain function with the callbacks can't be adapted to work this way and adding new functions isn't planned either.

**Comment by skoerfgen** [comment]
Update: I think I found a simple way to implement the 2-step-process. I'll keep you updated...

**Comment by Bizarrus** [comment]
Thats nice!

Yeah, I was thinking the same thing with the callbacks.

**Comment by skoerfgen** [comment]
Checkout the "delay"-branch: https://github.com/skoerfgen/ACMECert/tree/delay

In this version you can return false inside the handler function to tell ACMECert not to do the validation immediately. (see step1.php)

Later when the DNS settings are in place you call getCertificateChain again (using the same `$domain_config` as before) but this time without handler function. (see step2.php)

**Comment by skoerfgen** [comment]
Unfortunately the "simple way" I envisioned doesn't seem to work as expected :(

**Comment by Bizarrus** [comment]
I had seen your try on delay branch. I will try to solve these and make an push request

**Comment by Bizarrus** [comment]
Okay, it's complex, because you must store here the authorizations

**Comment by skoerfgen** [comment]
I gave it a second try and it works now! (at least I did not encounter any failures during testing)

https://github.com/skoerfgen/ACMECert/tree/steps

**Comment by Bizarrus** [comment]
i had the same thing but with another method. My idea was to pass an 4th parameter with following constant enums like:
```php
CertificateChainType::ONLY_CHALLENGES // to get the _acme-challenge tokens
CertificateChainType::COMMIT // Fire the post commit
null // default behavior
```

I will try your version, thanks for that!

**Comment by opiums9** [comment]
> I gave it a second try and it works now! (at least I did not encounter any failures during testing)
> 
> https://github.com/skoerfgen/ACMECert/tree/steps
> 
> Solution was to pass the order url from step1 to step2 and resume the order instead of creating a new one.

skoerfgen, thanks for the advice provided, there are some nuances.
This does not work on the latest version of ACMECert.
After lengthy troubleshooting, I was finally able to get the full chain for my server, but I found the unreliable Fake LE Root X1 there, I give the full code for clarity (revision may be required).

```
if(isset($_POST['postval']) && $_POST['postval'] == 'Generate_RSA_Public_Key'){
	$txt_rec = 'opiums.eu';
	require 'ACMECert.php';
	$ac = new ACMECert(false);
	$ac->loadAccountKey('file://'.'files/account_key.pem');

	$domain_config=array(
	  '*.'.$txt_rec=>array('challenge'=>'dns-01')
	);
	
	$privkey=$ac->generateRSAKey(2048);
	file_put_contents('files/cert_private_key.pem',$privkey);

	$handler=function($opts) use ($ac){
		echo 'Создайте DNS TXT запись '.$opts['key'].' со значением <b>'.$opts['value'].'</b><br />'.PHP_EOL;
		file_put_contents('files/newdns.txt',$opts['value']);
		return false;
	};
	
	$ret=$ac->getCertificateChain('file://'.'files/cert_private_key.pem',$domain_config,$handler);
	
	$order_url = $ret[0];
	$new_txt = file_get_contents('files/newdns.txt');
	$old_txt = get_txt_rec('_acme-challenge.'.$txt_rec);
	if($new_txt != $old_txt){
		echo 'Старая запись: '.$old_txt.'<br />'.PHP_EOL;
		echo 'Новая: <b>'.$new_txt.'</b><br />'.PHP_EOL;
		exit;
	}else{
		try{
			$fullchain=$ac->getCertificateChain('file://'.'files/cert_private_key.pem',$domain_config,$order_url);
			file_put_contents('files/fullchain.pem',$fullchain);
			echo '<b>Сертификат готов!</b>';
		}catch(ACME_Exception $e){
			$ac->log($e->getMessage()); // log original error
			foreach($e->getSubproblems() as $subproblem){
				$ac->log($subproblem->getMessage()); // log sub errors
			}
		}
	}
	exit;
}
```

**Comment by opiums9** [comment]
I found a reason! Need to replace 
`$ac = new ACMECert(false);`
on
`$ac = new ACMECert();`
thanks

**Comment by skoerfgen** [comment]
Update: There is another way to run getCertificateChain in two steps: https://github.com/skoerfgen/ACMECert/tree/delayed_validation

Have a look at the example: https://github.com/skoerfgen/ACMECert/blob/delayed_validation/example.php

(Due to authorization/order reuse there is no need to pass the order url from step1 to step2 anymore.)

**Comment by wumingpc** [comment]
It is convenient to consider the integration of most of the mainstream DNS service provider APIs like acme scripts, and then only need to configure DNS API parameters to issue certificates
