### ISSUE TITLE
Couldn't you provide a complete and simple example document? From the first step to the final certificate issuance and renewal, it feels like the order is confusing and there is no complete step by step, I don't know how the order is

### ISSUE THREAD

**Issue by wumingpc** [skoerfgen/ACMECert#44]
Couldn't you provide a complete and simple example document? From the first step to the final certificate issuance and renewal, it feels like the order is confusing and there is no complete step by step, I don't know how the order is

**Comment by skoerfgen** [comment]
Sure! Have a look at [Simple example to get started](https://github.com/skoerfgen/ACMECert/wiki/Simple-example-to-get-started)

**Comment by wumingpc** [comment]
This is http-01, need DNS verification method, and in which link to verify, how to achieve manual resolution after clicking the install button to verify, if using the API for DNS resolution record addition, time is too late? I would like to implement manual user resolution followed by manual operation to validate the request so that there are no errors

**Comment by skoerfgen** [comment]
Unfortunately, ACMECert is not designed for a two-step manual process. Its monolithic `getCertificateChain` function makes it challenging to achieve this without introducing messy code.

However you can delay the verification in the `$handler`function like this:

```php
$handler=function($opts) use ($ac){
  switch($opts['config']['challenge']){
    case 'dns-01': // manual example:
      echo 'Create DNS-TXT-Record '.$opts['key'].' with value '.$opts['value']."\n";
      readline('Press ENTER to continue to the verification..'); // wait here until user has manually set the challenge tokens
      return function($opts){
        echo 'Remove DNS-TXT-Record '.$opts['key'].' with value '.$opts['value']."\n";
      };
    break;
};
```

This way the challenge tokens are displayed and can be set manually by the user. Then when pressing ENTER it performs the validation.

**Comment by wumingpc** [comment]
I have tried the readline method, it seems to be useless to operate on the web page, this is only suitable for command debugging? Can I implement it via html+js, when the user gets the DNS resolution verification information, and then click the confirm button to verify the operation after manually resolving it?

**Comment by skoerfgen** [comment]
Yes, the `readline` function is indeed only useful on the command line (https://www.php.net/manual/en/features.commandline.php)

Unfortunately, ACMECert can't be used on an web page in this way, because it would require calling it two times. Once to display the verification information and the other one to trigger the validation and creation of the certificate. also on a web page you could run into issues like max_execution_time.

This would certainly be doable, but does not fit the design of ACMECert. Its goal is the be automated with no manual intervention needed.

I have tried this before, but abandoned it. Have a look at the [steps branch](https://github.com/skoerfgen/ACMECert/tree/steps). There is step1.php where it shows the validation information or gets the certificate immediately (if all authorizations are already valid) and step2.php gets the certificate (if step1.php returned the order url instead of a certificate).
You have to store the order url returned from step1.php and later pass it to step2.php.

**Comment by skoerfgen** [comment]
Related: https://github.com/skoerfgen/ACMECert/issues/4

**Comment by wumingpc** [comment]
> 
OK,Thanks！
